apiVersion: v1 
kind: Pod 
metadata:
  name: oslat
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  runtimeClassName: performance-cnv-sriov-profile
  restartPolicy: Never
  containers:
  - name: oslat 
    image: quay.io/jianzzha/oslat 
    imagePullPolicy: Always 
    resources:
      limits:
        memory: "200Mi"
        cpu: "4"
    env:
    - name: PRIO 
      value: "1"
    - name: delay
      value: "0"
    - name: RUNTIME_SECONDS 
      value: "30"
    - name: DISABLE_CPU_BALANCE
      value: "n"
      # DISABLE_CPU_BALANCE requires privileged=true
    - name: TRACE_THRESHOLD
      value: ""
      # TRACE_THRESHOLD requires privileged=true and debug volume
    securityContext:
      #privileged: true
      capabilities:
        fsGroup: 0
        add:
          - SYS_NICE
          - IPC_LOCK
          - SYS_RAWIO
          - SYS_ADMIN
    volumeMounts:
    - mountPath: /dev/cpu_dma_latency
      name: cstate
    #- mountPath: /sys/kernel/debug
    #  name: debug
  volumes:
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  #- name: debug
  #  hostPath:
  #    path: /sys/kernel/debug
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
